### ISSUE TITLE
pip installation is not compiling correctly

### ISSUE THREAD

**Issue by anonimauss** [Repast/repast4py#24]
### Overview

I am facing an error with the pip installation of `repast4py`. Error log attached. 
Installed on arch linux, with the latest `mpicxx` provided by both the official version by `openmpi` and the recommended one provided by `mpich`. The error outpud is the same regardless.      

`repast4py._core` compiles correctly but building `repast4py._space` crashes. 

### Details

`mpicxx --version`     **g++ (GCC) 12.1.0**   
`python --version`     **Python 3.10.4**   
`pip --version`              **pip 22.1**

The error is generated while compiling `SpatialTree.h`

```
In file included from src/repast4py/SpatialTree.cpp:7:
      src/repast4py/SpatialTree.h: In member function ‘std::shared_ptr<repast4py::STNode<BoxType, PointType> > repast4py::ComponentNode<BoxType, PointType>::split()’:
      src/repast4py/SpatialTree.h:148:41: error: ‘numeric_limits’ is not a member of ‘std’

```

A detailed log is provided below    

[`env CC=/opt/mpich/bin/mpicxx pip install repast4py`](https://github.com/Repast/repast4py/files/8679373/installation.log)
[`mpicxx -dumpspecs`](https://github.com/Repast/repast4py/files/8679411/mpicc_specs.log)

**Comment by ncollier** [comment]
I think this is probably due to some changes in gcc's std library include dependencies. Can you try to pip install the attached file.
[repast4py-1.0.4b1.tar.gz](https://github.com/Repast/repast4py/files/8679775/repast4py-1.0.4b1.tar.gz)

`pip install repast4py-1.0.4b1.tar.gz`

**Comment by anonimauss** [comment]
Works as expected. Thanks!
