### ISSUE TITLE
Installation Issue on WSL

### ISSUE THREAD

**Issue by dmehrab06** [Repast/repast4py#25]
I am using Windows subsystem for Linux (WSL) to install repast4py. I have installed `mpich` but when I run `env CC=mpicxx pip install repast4py`, I get the following error:

  ```
Could not find a version that satisfies the requirement repast4py (from versions: )
No matching distribution found for repast4py
```

**Comment by Alex98156** [comment]
Hello, i have the same issue running "env CC=mpicc pip3 install repast4py" i've also tried with "env CC=mpicc pip3 install repast4py --no-cache-dir "on ubuntu 20.04.1 running on VM. i have python 3.10.6 and pip 21.3.1 (downgraded) also mpi4py 3.1.3 installed via brew due problem installing it. i've followed  https://groups.google.com/g/mpi4py/c/PTKq6abLpNQ

First it shows "Installing build dependencies ... error" then the problem "ERROR: Failed building wheel for mpy4py" appears a couple of times before what dmehrab said.

![imagen](https://user-images.githubusercontent.com/65467169/188297503-7f9cb1dc-dcbc-4837-978f-8b18ec4b6b9d.png)
