### ISSUE TITLE
Support for Python 3.11

### ISSUE THREAD

**Issue by chris-dem** [Repast/repast4py#30]
## Describe the bug
 Unable to find longinter when using `env CC=mpicxx pip3.11 install repast4py` on ubuntu WSL

### To Reproduce

I followed the tutorial on https://repast.github.io/repast4py.site/guide/user_guide.html

### Expected behavior

Should have installed normally

### Logs/tracebacks

```python-traceback
In file included from src/MPI.c:4:
            src/mpi4py.MPI.c:198:12: fatal error: longintrepr.h: No such file or directory
              198 |   #include "longintrepr.h"
                  |            ^~~~~~~~~~~~~~~
            compilation terminated.
            error: command '/usr/bin/mpicc' failed with exit code 1
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for mpi4py
      Failed to build mpi4py
      ERROR: Could not build wheels for mpi4py, which is required to install pyproject.toml-based projects
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
```

### Python Version

```console
$ python --version
3.11
```

### OS

Ubuntu 20.04.5 LTS

**Comment by ncollier** [comment]
Thanks for the report. This looks like an incompatibility between mpi4py and python 3.11.  I think 3.11 is still a release candidate. So, if you can use 3.10 that would be a work around for now. In the meantime, we will do some testing with 3.11.

**Comment by ncollier** [comment]
I've tested with the released version of 3.11 on Ubuntu 22.04 and mpi4py now compiles, but numba and PyTorch aren't yet 3.11 compatible, so we need to wait on them.

**Comment by ncollier** [comment]
Numba release candidate for Python 3.11 is in testing:

https://github.com/numba/numba/issues/8841

**Comment by ncollier** [comment]
Numba and PyTorch are now 3.11 compatible so I've removed that restriction: https://github.com/Repast/repast4py/commit/0cfb33460ed3bf5c49c51b32a6b31dab994dc680
