### ISSUE TITLE
Bug in grid.get_agents(at)

### ISSUE THREAD

**Issue by Tortar** [Repast/repast4py#31]
Independently by the number of processes (even with just 1) if you run the example `zombies.py` changing in the .yaml the number of ticks to 1000 (depending on the size of the memory it could be less or more of course) gives you a memory error after a while because the memory usage increases tick by tick. 

I debugged it a bit and I found that the problem comes when you call `grid.get_agents(at)`, so I think there should be something going badly with the C extension of the space module.

**Comment by ncollier** [comment]
Thanks for the report. This is very helpful. We will look into it.

**Comment by Tortar** [comment]
I read the paper of repast4py and this bug could be critical to the performance comparison of the zombies model maybe

**Comment by ncollier** [comment]
I can reproduce this with tracemalloc.  Example code:

```python
for a in self.context.agents():
            pt = self.grid.get_location(a)
            sum = 0
            iter = self.grid.get_agents(pt)
            for other in iter:
                sum += other.id

            for other in iter:
                sum += other.id

            pt = self.grid.get_location(a)
            sum = 0
            for other in self.grid.get_agents(pt):
                sum += other.id
```

I think it's a bug in the reference counting for AgentIter. Working on fix.

**Comment by ncollier** [comment]
I think the memory leak should be fixed in this release. @Tortar, could you download and try your zombies run again with this? Without this fix, I can see the `get_agents` call leaking in zombies. With it, I don't observe that.  You can pip install from the archive with:

```
env CC=mpicxx pip install repast4py-1.0.5b1.tar.gz
```

Thanks.

[repast4py-1.0.5b1.tar.gz](https://github.com/Repast/repast4py/files/9789609/repast4py-1.0.5b1.tar.gz)

**Comment by Tortar** [comment]
yes, no problem, I will do that tomorrow because now I can't

**Comment by Tortar** [comment]
I tested and It works really well! I think It can be pushed to PyPI :-)

**Comment by Tortar** [comment]
Anyway I now ran the two versions to compare the times spent on zombies.py, I wasn't very rigorous (but I checked that maximum memory usage was at 80% so that not to have incomparable results). I see a 10% performance improvement in favor of the new version with 1 process 👍 . Don't know if the difference can be less or more severe in relation with the number of processes used.
