### ISSUE TITLE
can't find python.h on fresh ubuntu install

### ISSUE THREAD

**Issue by ric-colasanti** [Repast/repast4py#33]
Installing on a fresh  ubuntu install  I needed to install python3.8-dev first. ( throws the can't find python.h )
Just a sugesstion to add this to the documentation for ABM people new to python.  I know this is the same for all python libs that compile with C/C++. But it would be useful if it was mentioned in the docs. A lot of ABM people may be new to python and are trying this out or runnning someone elses model having only been given the instructions to go to Repast site and install Repast4py and probably on a new Ubintu install. ( We are going to do just this [ I will mention python3.8-dev in my notes to them ])
As I say just a sugestion. The docs are very good.

**Comment by ncollier** [comment]
Thanks for the report.  Can you post the error output? We are using just stock python and have not seen this so I’d like to look into it further.  Thanks.

**Comment by ncollier** [comment]
I've done some experiments and I haven't seen this when using the default 3.8  on ubuntu 20.04. However, when using a non-default package, 3.7 and 3.9 in this case, I do see the error. I'll update the docs to reflect this. Thanks again.

**Comment by ncollier** [comment]
Updated docs in 7304751
