### ISSUE TITLE
Bug: Hardcoded arguments the SharedValueLayer Class

### ISSUE THREAD

**Issue by ajford-23** [Repast/repast4py#38]
The child class, `SharedValueLayer`, takes `init_value` as an argument, but does not pass this onto the parent class. Instead, 'random' is passed on. As a result, the `grid` property contains an incorrectly sized tensor and random values. 

https://github.com/Repast/repast4py/blob/67a456da091223f37727cc66fbfc908f01cf4660/src/repast4py/value_layer.py#L505

**Comment by ncollier** [comment]
Thanks for the report. I'll fix this right away.

**Comment by ncollier** [comment]
@ajford-23 I just had a quick look at this, and although the parent class constructor is called with 'random' , the initial value is set later in the SharedValue constructor here https://github.com/Repast/repast4py/blob/67a456da091223f37727cc66fbfc908f01cf4660/src/repast4py/value_layer.py#L526

Many of the unit tests for SharedValueLayer set the initial value to the current process rank then test for that. Those are currently passing. 

Can you say more about when you are seeing random values, so we can fix that case? Thanks.

**Comment by ajford-23** [comment]
Thanks for getting back so quickly!  I am coming in with the assumptions that:

1. The initial value used to create a SharedValueLayer object must already be broken down into appropriate chunks for each rank process, since `local_bounds` are used to index `grid` in  `_init_value.`
https://github.com/Repast/repast4py/blob/67a456da091223f37727cc66fbfc908f01cf4660/src/repast4py/value_layer.py#L535
2. A `SharedValueLayer` object should be initialized within the Model class. 
3. The BoundingBox argument for SharedValueLayer should be that of the whole world. 

With these assumption, I tried to run a simulation of a 100x100 word with 4 ranks. I expected SharedValueLayer.grid to return a 100x100 tensor, but instead got a 142x142 tensor. Calls on SharedValueLayer.grid from different ranks also yield different tensors, with chunks from initial values on one of four corners.

**Comment by ajford-23** [comment]
Here is the code snippet I am using to create a SharedValueLayer.
`...`
`box = space.BoundingBox(0, params['world.width'], 0, params['world.height'], 0, 0)`
`...`
`self.foodValue = repast4py.value_layer.SharedValueLayer(comm, box, borders=space.BorderType.Sticky, buffer_size = DMAX
         ,init_value = onRankFood)`
`...`
I also only see issues when I execute the code using `mpirun -n 4 python project.py project.yaml `. 
Thanks

**Comment by ncollier** [comment]
I've added buffer synchronization to the value layer initialization that fills the buffers appropriately during value layer construction, and a unit test that tests for the appropriate value in the buffers. This test failing prior to the auto-synchronization addition. Fixed in cc1cb43. Previously existing tests assume user would to do a synch before using the value layer which is a bad assumption.
