### ISSUE TITLE
A bug in DirectedSharedNetwork.graph

### ISSUE THREAD

**Issue by ak2495** [Repast/repast4py#40]
Let's assume we have a directed network with 3 nodes in 3 different processors (ranks). For instance, consider the following network.

network 1
1 0 0
2 0 1
3 0 2
EDGES
1 2
1 3

For finding the neighboring nodes with DirectedSharedNetwork.graph.successors() or predecessors(), it will return agents from one rank and ignore neighboring agents in other ranks. for example

DirectedSharedNetwork.graph.successors(self.context.agent(1,0,0))

will return Agent(3,0,2) and not [Agent(3,0,2) , Agent(2,0,1)]. This is also the case with the undirected graph and UndirectedSharedNetwork.graph.neighbors(). Therefore I also think the rumor example results are not correct.

**Comment by ncollier** [comment]
Can you say more how you tested? I wrote a quick unit test and things appear to be working

```python
def testNghs(self):
      comm = MPI.COMM_WORLD
      rank = comm.Get_rank()
      context = ctx.SharedContext(comm)

      fpath = './test_data/simple_net.txt'
      read_network(fpath, context, construct_agent, restore_agent)
      g = context.get_projection("network")
      self.assertTrue(g.is_directed)

      if rank == 0:
          ss = [n.uid for n in g.graph.successors(context.agent((1, 0, 0)))]
          self.assertEqual(2, len(ss))
          self.assertTrue((3, 0, 2) in ss)
          self.assertTrue((2, 0, 1) in ss)
          print(ss)
```
The tests pass and the output is `[(2, 0, 1), (3, 0, 2)]`
