### ISSUE TITLE
Cascading splits in spatial tree code

### ISSUE THREAD

**Issue by ncollier** [Repast/repast4py#49]
We use a quad tree in the continuous space for efficient bounds queries, which are necessary when populating the buffered areas between processes, and for fast (or at least faster) get_agents_within queries. The threshold argument to the SharedCSpace specifies  the maximum capacity for a node in the tree. When this capacity is met, the node splits, and the agent locations in that node are allocated to the newly created children. When the number of agents at a single point >= the threshold, the splitting will occur every time an agent is added to that point. The splitting also doesn’t actually accomplish anything, given that agents are all on a single point.  The branch at that point gets longer and longer, and so the time it takes to add (and to a lesser extent to remove) agents also takes longer and longer.

Possible Fixes:

1. Make sure user has large enough threshold - warning message when some tree depth is reached
2. Threshold should be for number of different points in the node's items rather than raw agent count
3.  User specifiable max depth
4. Allow user to choose among these with 1. being a default

Note that 2. would require storing the number of agents at each point and incrementing / decrementing that when agents are added and removed.

**Comment by jozik** [comment]
Thinking we do 2, and add documentation in a performance consideration section where we guide the users on threshold setting and max depth.

**Comment by ncollier** [comment]
- [ ] "Item" class for single occupancy
- [ ] "Item" class for multiple occupancy
- [ ] Units for "item" classes
- [ ] Spatial Tree updates to select the correct item class via template
- [ ] Python within tests -- maybe debug compile arg that prints out tree depth

**Comment by ncollier** [comment]
New spatial tree code performs well with different thresholds.  

Model Specs:

* 30K agents on each rank
* 120 unique points on each rank
* Average of 250 agents at each point


2 million (no split): 

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>tick</th>
      <th>rank</th>
      <th>n_agents</th>
      <th>step_time</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>0</td>
      <td>30000</td>
      <td>0.182510</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2</td>
      <td>0</td>
      <td>30000</td>
      <td>0.146904</td>
    </tr>
    <tr>
      <th>2</th>
      <td>3</td>
      <td>0</td>
      <td>30000</td>
      <td>0.152098</td>
    </tr>
    <tr>
      <th>3</th>
      <td>4</td>
      <td>0</td>
      <td>30000</td>
      <td>0.151333</td>
    </tr>
    <tr>
      <th>4</th>
      <td>5</td>
      <td>0</td>
      <td>30000</td>
      <td>0.151210</td>
    </tr>
    <tr>
      <th>5</th>
      <td>6</td>
      <td>0</td>
      <td>30000</td>
      <td>0.152491</td>
    </tr>
    <tr>
      <th>6</th>
      <td>7</td>
      <td>0</td>
      <td>30000</td>
      <td>0.150645</td>
    </tr>
    <tr>
      <th>7</th>
      <td>8</td>
      <td>0</td>
      <td>30000</td>
      <td>0.158630</td>
    </tr>
    <tr>
      <th>8</th>
      <td>9</td>
      <td>0</td>
      <td>30000</td>
      <td>0.151703</td>
    </tr>
    <tr>
      <th>9</th>
      <td>10</td>
      <td>0</td>
      <td>30000</td>
      <td>0.152366</td>
    </tr>
  </tbody>
</table>
</div>

50 (~5 splits):

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>tick</th>
      <th>rank</th>
      <th>n_agents</th>
      <th>step_time</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>0</td>
      <td>30000</td>
      <td>0.189951</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2</td>
      <td>0</td>
      <td>30000</td>
      <td>0.143431</td>
    </tr>
    <tr>
      <th>2</th>
      <td>3</td>
      <td>0</td>
      <td>30000</td>
      <td>0.151155</td>
    </tr>
    <tr>
      <th>3</th>
      <td>4</td>
      <td>0</td>
      <td>30000</td>
      <td>0.161553</td>
    </tr>
    <tr>
      <th>4</th>
      <td>5</td>
      <td>0</td>
      <td>30000</td>
      <td>0.157767</td>
    </tr>
    <tr>
      <th>5</th>
      <td>6</td>
      <td>0</td>
      <td>30000</td>
      <td>0.158458</td>
    </tr>
    <tr>
      <th>6</th>
      <td>7</td>
      <td>0</td>
      <td>30000</td>
      <td>0.160554</td>
    </tr>
    <tr>
      <th>7</th>
      <td>8</td>
      <td>0</td>
      <td>30000</td>
      <td>0.171164</td>
    </tr>
    <tr>
      <th>8</th>
      <td>9</td>
      <td>0</td>
      <td>30000</td>
      <td>0.166341</td>
    </tr>
    <tr>
      <th>9</th>
      <td>10</td>
      <td>0</td>
      <td>30000</td>
      <td>0.164225</td>
    </tr>
  </tbody>
</table>
</div>

Old Code (cascading splits):

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>tick</th>
      <th>rank</th>
      <th>n_agents</th>
      <th>step_time</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>0</td>
      <td>30000</td>
      <td>2.713310</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2</td>
      <td>0</td>
      <td>30000</td>
      <td>8.957481</td>
    </tr>
    <tr>
      <th>2</th>
      <td>3</td>
      <td>0</td>
      <td>30000</td>
      <td>12.435087</td>
    </tr>
    <tr>
      <th>3</th>
      <td>4</td>
      <td>0</td>
      <td>30000</td>
      <td>16.045948</td>
    </tr>
    <tr>
      <th>4</th>
      <td>5</td>
      <td>0</td>
      <td>30000</td>
      <td>19.560941</td>
    </tr>
    <tr>
      <th>5</th>
      <td>6</td>
      <td>0</td>
      <td>30000</td>
      <td>23.257516</td>
    </tr>
    <tr>
      <th>6</th>
      <td>7</td>
      <td>0</td>
      <td>30000</td>
      <td>26.905862</td>
    </tr>
    <tr>
      <th>7</th>
      <td>8</td>
      <td>0</td>
      <td>30000</td>
      <td>30.622496</td>
    </tr>
    <tr>
      <th>8</th>
      <td>9</td>
      <td>0</td>
      <td>30000</td>
      <td>34.408759</td>
    </tr>
    <tr>
      <th>9</th>
      <td>10</td>
      <td>0</td>
      <td>30000</td>
      <td>38.221699</td>
    </tr>
  </tbody>
</table>
</div>

**Comment by ncollier** [comment]
Re-opening. Spatial tree "items" classes duplicate the storage aspects of the "location_maps" in the space itself. Refactored to use the location maps.

- [ ] Update cpp unit tests
- [ ] Update `split` implementation to work with just points 
- [ ] Remove items collections
- [ ] Test with spatial tree test on Bebop and see if get comparable runtimes to the above.

**Comment by ncollier** [comment]
Merged into develop - 72dfbb8
