### ISSUE TITLE
Missing mpi.h file error even with python-dev package installed

### ISSUE THREAD

**Issue by DanieleRavasi** [Repast/repast4py#70]
**OS**: Ubuntu22.04.5 on WSL2 for Win 11

**Python version**: 3.11.10

**Python-dev version**: 3.11-dev

**MPI4py version**: mpich4.0.3

**Error Message**:

`src/repast4py/geometry.h:13:10: fatal error: mpi.h: No such file or directory
         13 | #include <mpi.h>
            |          ^~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-g++' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for repast4py
Failed to build repast4py
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (repast4py)`

**Code which generates the error**: 
`sudo env CC=mpicxx pip install repast4py`

**Comment by DanieleRavasi** [comment]
I used the command provided in the repast4py guide

Il lun 16 set 2024, 18:15 Nick Collier ***@***.***> ha
scritto:

**Comment by ncollier** [comment]
@DanieleRavasi Can you run this command?

```
mpicxx -show
```

You should see something like:

```
g++ -Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -I/usr/include/aarch64-linux-gnu/mpich -L/usr/lib/aarch64-linux-gnu -lmpichcxx -lmpich
```

Note the aarch64 directory will probably be different for you, but you can use that output to `ls` the include directory (the one prefixed with `-I`):

```
ls /usr/include/aarch64-linux-gnu/mpich
```

You should see `mpi.h` in there. 

If not, perhaps the mpi development components aren't being installed with just `mpich`. In which case, you could try:

```
apt install libmpich-dev 
```

If that we works, we can update the docs to reflect it.

**Comment by DanieleRavasi** [comment]
Thank you for your help,

I tried and using the command you provided me it appears that mpi.h is
correctly installed. I tried installing the dev components anyway and it
appears there are no missing packages. I keep getting the same error

Il giorno lun 16 set 2024 alle ore 22:15 Nick Collier <
***@***.***> ha scritto:

**Comment by ncollier** [comment]
Will we try to reproduce your error, but in the meantime, can you try:

```
env CC=mpicxx CXX=mpicxx pip install repast4py
```

Also, I'm assuming mpi4py installed correctly? You didn't get any errors from that?

**Comment by DanieleRavasi** [comment]
Seems like the last line of code worked, thank you!

Do you want me to check the git hub post I opened as solved?



Il giorno mar 17 set 2024 alle ore 14:36 Nick Collier <
***@***.***> ha scritto:

**Comment by ncollier** [comment]
@DanieleRavasi. Thanks.  I'll close this after I've updated the documentation to reflect it.

**Comment by DanieleRavasi** [comment]
Update: I am running a test model in single thread, it's compiling, thank
again for your time and patience

Il mar 17 set 2024, 15:26 Nick Collier ***@***.***> ha
scritto:

**Comment by ncollier** [comment]
Updated docs to include CXX=mpicxx and mention that it might be necessary.
