### ISSUE TITLE
How to combine landcover with repast4py grid

### ISSUE THREAD

**Issue by RoryMMMM** [Repast/repast4py#74]
I'm trying to create a model with agents that are aware of their environment, as well as other agents. I would like to be able to be able to specify a region of interest, import files that cover that region, and then have agents interact within the region and base their movement on land cover variables associated with their location/neighbouring locations. Something like:

1. Initialise SharedCSpace and/or SharedGrid that covers area of interest
2. Download geotiff file/geojson/array from https://www.mrlc.gov/ that covers same region
3. Load geotiff values into SharedCSpace, grid or custom object
4. Agents move based on values from geotiff, other nearby agents, values from geotiff for nearby grid cells  

I've been looking at the docs and I'm not certain how to link the repast grid/space objects to geotiff values, the Zombies example shows how to do grid searches based on neighbouring agents, but not about stored values describing neighbouring cells. I'm hesitent to write custom code on this since the geospatial data is going to get large, and I don't want to have it duplicated across ranks, and I'm new to mpi coding so the chance of duplication is high... 

Any ideas on how to tackle this?

**Comment by RoryMMMM** [comment]
So it seems that I should be looking at **repast4py.value_layer** or **repast4py.value_layer.SharedValueLayer** to hold and share the raster data. My issue has now changed a little bit, I've been using web-mercator projection to have my rasters, GPS data etc in meters. This made my bounding box around 20k x 30k, for my area of study, and the SharedValueLayer uses the bounding box to initialise the array. So I end up with an array that is 20k x 30k big, holding a 30m resultion image. This makes the array about 100x bigger than needed.

I should probably figure out how to reduce my simulation bounding box...

**Comment by ncollier** [comment]
Yes, the SharedValueLayer is intended for that kind of raster data.

**Comment by RoryMMMM** [comment]
Is there a way to set the array in the SharedValueLayer. What I'm trying:

``` 
# Use OWSLib and Rasterio to fetch data, and return it as numpy array + meter_per_pixel tuple
canopy_array, xy_resolution = fetch_img()

>>> canopy_array =
array([[[21, 25, 33, ..., 16,  0,  0],
        [ 0,  0, 28, ...,  0,  0,  0],
        [17,  0, 25, ..., 64, 54, 48],
        ...,
        [32, 38, 65, ..., 15, 10, 18],
        [74, 71, 87, ..., 27, 29, 28],
        [83, 75, 81, ..., 31, 29, 29]]], dtype=uint8)

# Convert projection units to pixel units. Raster has size of (1,30,30) for example
projection_bounds = space.BoundingBox(0, 
                            canopy_array.shape[1], 
                            0, 
                            canopy_array.shape[2], 
                            0, 
                            0) 
 
# Create SharedValue Layer
canopy_layer = SharedValueLayer(comm = comm, 
                                bounds = projection_bounds, 
                                borders = space.BorderType.Sticky, 
                                buffer_size = 2, 
                                init_value = 0)

# Convert numpy array to torch tensor
canopy_layer.grid = torch.from_numpy(canopy_array).type(torch.float64)
```

Returns and error  ```AttributeError: property 'grid' of 'SharedValueLayer' object has no setter ```. It looks like that the only way to set values in a shared_array would be in a loop useing ```canopy_layer.set(self, pt: DiscretePoint, val)```, that right?

**Comment by ncollier** [comment]
Using `set` should work. But also `grid` gives you the tensor, but you can't replace that with one of you own. But you should be able to update its values using PyTorch slicing -- e.g. `grid[:, :] = canopy_array[:,:]` . However, the grid tensor includes the buffer zone, so that slicing example won't work correctly, if you are running on more than 1 rank. At any rate, check the shape of the grid, and if it doesn't match that of the canopy_array, using set will be safer.

**Comment by RoryMMMM** [comment]
This will end up running with more than 1 rank so I'll have to figure out how to: loop through each (x,y) coordinate in each rank, and then

**Comment by RoryMMMM** [comment]
Wasn't that tough! 

I used the shared_layer.bounds object to figure out which pixels of the large raster needed to get associated with each rank.  

Here's what I ended up doing. Seems to work with multiple ranks but need to do some work on translating pixel locations to geographic locations to double check:
```

def setup_repast_spatial(self):
        '''
        Return a shared grid, shared continuous space and a shared value layer/s
        that contain a space for agents to move on and
        a grid for agents to look for neighbours on (similar to zombie example)
        and a shared layer to hold geotiff data. 

        Because of limitation on the way repast handles grids the grid will be
        scaled to the raster resolution. 
        ''' 
       ...
       # Returns a (row,column,band) array from geotiff + (meters_per_x_pixel, meters_per_y_pixel) tuple
       # Using WCS call to geoserver.
        canopy_array, self.xy_resolution = fetch_img.fetch_img(canopy) 

        log.info(f'WCS Array shape: {canopy_array.shape}')
        # Convert projection units to pixel units:
        projection_bounds = space.BoundingBox(0, 
                                    canopy_array.shape[1], 
                                    0, 
                                    canopy_array.shape[0], 
                                    0, 
                                    0)  

        log.info(f'Total Projection bounds: {projection_bounds}')

        self.canopy_layer = SharedValueLayer(comm = self.comm, 
                                        bounds = projection_bounds, 
                                        borders = space.BorderType.Sticky, 
                                        buffer_size = int(params['geo']['buffer_size']), 
                                        init_value = 0)
        log.info(f'This Rank Projection bounds: {self.canopy_layer.bounds}')
 
       # canopy_layer bounds are now different for each rank:
       # Example for a 2 rank sim: 
        xy = [self.canopy_layer.bounds.ymin, 
              self.canopy_layer.bounds.ymin + self.canopy_layer.bounds.yextent,
              self.canopy_layer.bounds.xmin, 
              self.canopy_layer.bounds.xmin + self.canopy_layer.bounds.xextent ] 
        
        sub_array = canopy_array[xy[0]:xy[1],xy[2]:xy[3],0] 
        self.canopy_layer.grid[:,:] = torch.from_numpy(sub_array).type(torch.float64)
        self.context.add_value_layer(self.canopy_layer)
        ...
```

results:
```

2024-11-26 17:39:01,241   4586 MainThread ::INFO     WCS Array shape: (773, 1115, 1)
2024-11-26 17:39:01,241   4586 MainThread ::INFO     Total Projection bounds: BoundingBox(xmin=0, xextent=1115, ymin=0, yextent=773, zmin=0, zextent=0)
2024-11-26 17:39:02,034   5376 MainThread ::INFO     WCS Array shape: (773, 1115, 1)
2024-11-26 17:39:02,034   5376 MainThread ::INFO     Total Projection bounds: BoundingBox(xmin=0, xextent=1115, ymin=0, yextent=773, zmin=0, zextent=0)
2024-11-26 17:39:02,040   5382 MainThread ::INFO     This Rank Projection bounds: BoundingBox(xmin=0, xextent=658, ymin=0, yextent=773, zmin=0, zextent=0)
2024-11-26 17:39:02,040   5385 MainThread ::INFO     This Rank Projection bounds: BoundingBox(xmin=458, xextent=657, ymin=0, yextent=773, zmin=0, zextent=0)
```

**Comment by RoryMMMM** [comment]
Looks like the Y-Axis is flipped in the above example. But that shouldn't be too tough to fix:

![image](https://github.com/user-attachments/assets/6f267058-afc6-44d1-a5da-a5e3493922de)

**Comment by ncollier** [comment]
@RoryMMMM thanks for posting the solution! Hopefully that will be to others later.

**Comment by RoryMMMM** [comment]
I'm hoping to post the entire git repo once published. It might make a nice example.

**Comment by ncollier** [comment]
That's excellent. Please let us know if / when you do.
